version: 1.0.{build}
image: Visual Studio 2017

configuration:
  - Debug
  - Release

platform:
  - Win32
  - x64
  - MinGW

# see "Skip commits" at https://www.appveyor.com/docs/how-to/filtering-commits/#commit-files-github-and-bitbucket-only
skip_commits:
  files:
    - '*.md'
    - .gitignore
    - .editorconfig
    - 'azure-pipelines*.yml'
    - 'ci/azure-pipelines/template*.yml'
    - '.github/*.md'
    - '.github/ISSUE_TEMPLATE/*.md'

install:
- cmd: |
    pip install openpyxl --user
    C:\msys64\usr\bin\bash --login -c "pacman -S --noconfirm mingw-w64-x86_64-gtest"

build_script:
- cmd: |
    build-all.bat %PLATFORM% %CONFIGURATION%
    tests\build-and-test.bat %PLATFORM% %CONFIGURATION%

for:
-
  matrix:
    only:
      - platform: Win32
      - platform: x64

  artifacts:
    - path: 'sakura-*$(platform)-$(configuration)*.zip*'
    - path: 'sha256.txt'
