version: 1.0.{build}
image: Visual Studio 2017

configuration:
  - Debug
  - Release

platform:
  - Win32
  - x64
  - MinGW

# see "Skip commits" at https://www.appveyor.com/docs/how-to/filtering-commits/#commit-files-github-and-bitbucket-only
skip_commits:
  files:
    - '*.md'
    - .gitignore
    - .editorconfig
    - 'azure-pipelines*.yml'
    - 'ci/azure-pipelines/template*.yml'

environment:
  matrix:
    - SONAR_QUBE: Yes
    - SONAR_QUBE: No

matrix:
  exclude:
    - configuration: Release
      SONAR_QUBE: Yes

install:
- cmd: |
    pip install openpyxl --user
    choco install "msbuild-sonarqube-runner" -y

build_script:
- cmd: |
    build-all.bat %PLATFORM% %CONFIGURATION%
    tests\build-and-test.bat %PLATFORM% %CONFIGURATION%

artifacts:
  - path: 'sakura-*$(platform)-$(configuration)*.zip'
  - path: 'sakura-*$(platform)-$(configuration)*.zip.md5'
  - path: 'sha256.txt'
