version: 1.0.{build}
image: Visual Studio 2017

configuration:
  - Release
  - Debug

platform:
  - Win32
  - x64
  - MinGW

install:
- cmd: >-
    msiexec /i externals\cppcheck\cppcheck-1.84-x64-Setup.msi /quiet /qn /norestart /log cppcheck-install.log

    externals\doxygen\doxygen-1.8.14-setup.exe /silent /suppressmsgboxes

build_script:
- cmd: >-
    call checkEncoding.bat

    call build-all.bat %PLATFORM% %CONFIGURATION%

    call tests\build-and-test.bat %PLATFORM% %CONFIGURATION%

artifacts:
- path: 'sakura-*$(platform)-$(configuration)*.zip'
