version: 1.0.{build}
image: Visual Studio 2017
clone_folder: C:\projects\$(APPVEYOR_ACCOUNT_NAME)\$(APPVEYOR_PROJECT_NAME)_$(APPVEYOR_BUILD_VERSION)
init:
- ps: Set-WinSystemLocale ja-JP
- ps: Start-Sleep -s 5
- ps: Restart-Computer
- ps: Start-Sleep -s 5

configuration:
  - Release
  - Debug

platform:
  - Win32

build_script:
- cmd: >-
    set SLN_FILE=sakura.sln

    echo PLATFORM      %PLATFORM%

    echo CONFIGURATION %CONFIGURATION%

    set EXTRA_CMD=/verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

    set MSBUILD_EXE="C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe"



    echo %MSBUILD_EXE% %SLN_FILE% /p:Platform=%PLATFORM% /p:Configuration=%CONFIGURATION%      /t:"Clean","Rebuild"  %EXTRA_CMD%
         %MSBUILD_EXE% %SLN_FILE% /p:Platform=%PLATFORM% /p:Configuration=%CONFIGURATION%      /t:"Clean","Rebuild"  %EXTRA_CMD%

    echo appveyor_yml

artifacts:
- path: '$(platform)\$(configuration)\*.exe'
- path: '$(platform)\$(configuration)\*.dll'
- path: '$(platform)\$(configuration)\*.pdb'
