###############################################################################################################################
#   ビルドトリガー (branch)
#
#   https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&viewFallbackFrom=vsts&tabs=yaml
###############################################################################################################################
trigger:
  branches:
    include:
      - master
      - develop
      - feature/*
  paths:
    exclude:
      - "*.md"
      - .travis.yml
      - appveyor.yml

###############################################################################################################################
#   ビルドトリガー (Pull Request)
#
#   https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml#pull-request-validation
###############################################################################################################################
pr:
  branches:
    include:
      - master
      - develop
      - feature/*

###############################################################################################################################
#   jobs/job 定義
#
#   https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml
###############################################################################################################################
jobs:

# サクラエディタのビルドを行う JOB
# * サクラエディタ本体
# * HTML Help
# * Installer
# * 単体テスト
- template: ci/azure-pipelines/template.job.build-unittest.yml
  parameters:
    name: VS2017
    vmImage: 'VS2017-Win2016'
    displayName: VS2017

# SonarQube を行う JOB
- job: SonarQube
  displayName: 'SonarQube'
  pool:
    vmImage: 'VS2017-Win2016'

  strategy:
    maxParallel: 4
    matrix:
      Win32_Debug:
        BuildPlatform: 'Win32'
        Configuration: 'Debug'
      Win32_Release:
        BuildPlatform: 'Win32'
        Configuration: 'Release'
      Win64_Debug:
        BuildPlatform: 'x64'
        Configuration: 'Debug'
      Win64_Release:
        BuildPlatform: 'x64'
        Configuration: 'Release'

  # https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch
  variables:
    SONAR_QUBE: Yes

  # set condition    at https://docs.microsoft.com/ja-jp/azure/devops/pipelines/process/conditions?view=azure-devops&viewFallbackFrom=vsts&tabs=yaml
  # see Build.Reason at https://docs.microsoft.com/ja-jp/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml
  condition: eq(variables['Build.Reason'], 'Schedule')

  steps:
  - template: ci/azure-pipelines/template-build-sonarqube.yml

# Cppcheck を行う JOB
- template: ci/azure-pipelines/template.job.cppcheck.yml
  parameters:
    name: cppcheck
    vmImage: 'VS2017-Win2016'
    displayName: cppcheck

# doxygen を行う JOB
- template: ci/azure-pipelines/template.job.doxygen.yml
  parameters:
    name: doxygen
    vmImage: 'VS2017-Win2016'
    displayName: doxygen

# 文字コードのチェックを行う JOB
- template: ci/azure-pipelines/template.job.checkEncoding.yml
  parameters:
    name: checkEncoding
    vmImage: 'VS2017-Win2016'

#############################################################################################################
#   Python スクリプトのコンパイル確認を行う job
#############################################################################################################
- template: ci/azure-pipelines/template.job.python-check.yml
  parameters:
    name: script_check
    vmImage: 'VS2017-Win2016'
    displayName: script_check
