###############################################################################################################################
#   ビルドトリガー (branch)
#
#   https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&viewFallbackFrom=vsts&tabs=yaml
###############################################################################################################################
trigger:
  branches:
    include:
      - master
      - develop
      - feature/*
  paths:
    exclude:
      - "*.md"
      - .travis.yml
      - appveyor.yml

###############################################################################################################################
#   ビルドトリガー (Pull Request)
#
#   https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml#pull-request-validation
###############################################################################################################################
pr:
  branches:
    include:
      - master
      - develop
      - feature/*

###############################################################################################################################
#   jobs/job 定義
#
#   https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml
###############################################################################################################################
jobs:

# サクラエディタのビルドを行う JOB
# * サクラエディタ本体
# * HTML Help
# * Installer
# * 単体テスト
- template: ci/azure-pipelines/template.job.build-unittest.yml
  parameters:
    name: VS2017
    vmImage: 'VS2017-Win2016'

# Cppcheck を行う JOB
- job: cppcheck
  displayName: 'Windows cppcheck'
  pool:
    vmImage: 'VS2017-Win2016'

  strategy:
    maxParallel: 2
    matrix:
      Win32_Release:
        BuildPlatform: 'Win32'
        Configuration: 'Release'
      Win64_Release:
        BuildPlatform: 'x64'
        Configuration: 'Release'

  steps:
  - template: ci/azure-pipelines/template.job.cppcheck.yml

# doxygen を行う JOB
- job: doxygen
  displayName: 'Windows doxygen'
  pool:
    vmImage: 'VS2017-Win2016'

  strategy:
    maxParallel: 2
    matrix:
      Win32_Release:
        BuildPlatform: 'Win32'
        Configuration: 'Release'
      Win64_Release:
        BuildPlatform: 'x64'
        Configuration: 'Release'

  steps:
  - template: ci/azure-pipelines/template.job.doxygen.yml

# 文字コードのチェックを行う JOB
- job: checkEncoding
  displayName: 'Windows checkEncoding'
  pool:
    vmImage: 'VS2017-Win2016'

  steps:
  - template: ci/azure-pipelines/template.job.checkEncoding.yml
