steps:
# show environmental variables for debug.
- script: set
  displayName: Show environmental variables for debug

# Build solution
- script: build-sln.bat       $(BuildPlatform) $(Configuration)
  displayName: Build solution

# Build HTML Help
- script: build-chm.bat
  displayName: Build HTML Help

# Build instaler with Inno Setup
- script: build-installer.bat $(BuildPlatform) $(Configuration)
  displayName: Build instaler with Inno Setup

# Run cppcheck
- script: run-cppcheck.bat    $(BuildPlatform) $(Configuration)
  displayName: Run cppcheck

# Run doxygen
- script: run-doxygen.bat     $(BuildPlatform) $(Configuration)
  displayName: Run doxygen

# zip files for artifacts
- script: zipArtifacts.bat    $(BuildPlatform) $(Configuration)
  displayName: Zip files for artifacts

# see https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/copy-files?view=azure-devops&tabs=yaml
- task: CopyFiles@1
  displayName: Copy to ArtifactStagingDirectory
  inputs:
    contents: '**.zip'
    targetFolder: $(Build.ArtifactStagingDirectory)

# see https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/build-artifacts?view=azure-devops&tabs=yaml
- task: PublishBuildArtifacts@1
  displayName: Publish ArtifactStagingDirectory
  inputs:
     pathtoPublish: '$(Build.ArtifactStagingDirectory)'
     artifactName: $(BuildPlatform)_$(Configuration)
