#############################################################################################################
#   Python のコンパイルチェックを行う 'steps' を定義するテンプレート
#
#   parameters
#       versionSpec  : Python のバージョン
#       architecture : Python のアーキテクチャ
#
#############################################################################################################
parameters:
  # defaults parameters
  versionSpec: '2.7'
  architecture: 'x64'

steps:
  # https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/use-python-version?view=azure-devops
  - task: UsePythonVersion@0
    displayName: UsePythonVersion ${{ parameters.versionSpec }} ${{ parameters.architecture }}
    inputs:
       versionSpec:  ${{ parameters.versionSpec }}
       architecture: ${{ parameters.architecture }}

  - script: python --version
    displayName: version check ${{ parameters.versionSpec }} ${{ parameters.architecture }}

  - script: python -m compileall -f .
    displayName: python compile check before install ${{ parameters.versionSpec }} ${{ parameters.architecture }}

  - template: /ci/azure-pipelines/template.steps.install-python-modules.yml

  - script: python -m compileall -f .
    displayName: python compile check after install  ${{ parameters.versionSpec }} ${{ parameters.architecture }}
